### ISSUE TITLE
Repacking successful but kernel doesn't boot

### ISSUE THREAD

**Issue by BlueMax** [xiaolu/mkbootimg_tools#10]
Repacking [this 5.1.1 kernel](http://arter97.com/browse/S4/kernel/AOSP_Lollipop-5.1/6.0/arter97-kernel-i9506-6.0.zip) (without changing anything) works properly but it doesn't boot (just hangs at bootloader screen on Galaxy S4 LTE). 

Any idea what's wrong?

**Comment by xiaolu** [comment]
try:
        cd $ramdisk; find . | fakeroot cpio -R 0:0 -H newc -o 2>/dev/null \
            | $zcommand > $unpacked_dir/new_ramdisk; cd $unpacked_dir
        #$mkbootfs $ramdisk | $zcommand > new_ramdisk

**Comment by BlueMax** [comment]
I guess uncommenting line 143/144 in current 'mkboot' will do the same. I can test it earliest in probably 24/48h on next kernel release. I had to temporarily fall back to older rom. Will report back as soon as possible.

**Comment by BlueMax** [comment]
No, unfortunately doesn't work.

**Comment by xiaolu** [comment]
cd $ramdisk; find . | fakeroot cpio -H newc -o 2>/dev/null \
            | $zcommand > $unpacked_dir/new_ramdisk; cd $unpacked_dir

@BlueMax

**Comment by BlueMax** [comment]
:+1: 
You were already right in the first place (2nd post). Stupid me forgot to comment out '$mkbootfs $ramdisk | $zcommand > new_ramdisk' so it didn't have any effect indeed. 
It does work properly now. I haven't tested your 2nd commandline with revised arguments yet. I guess its not necessary anymore.
Thank you very much and sorry for any inconvenience.
