### ISSUE TITLE
How to pack my own ZImage (kernel) to a new boot.img

### ISSUE THREAD

**Issue by hkfriends** [xiaolu/mkbootimg_tools#2]
Hi there

I can use your tools to unpack stock boot.img to zImage and ramdisk... then I can make change to ramdisk and then re-pack ok .... very good!!

unfortunately I have download kernel source and re-build (customize) my kernel and build new zImage

but I cannot pack my own (new) zImage and the ramdisk, I belive dt.img need to re-build.... 

can you tell me how to use your script to do that? it seems no paramter for me to pass dt.img path

大大, 簡單的是怎樣把我自己compile的kernel (zImage), 合拼ramdisk + dt.img 為boot.img ?
貌似dt.img 要compile過, 同時你的script不能指特定zImage 戓 dt.img
謝謝幫忙

**Comment by NikitaProAndroid** [comment]
Hello  xiaolu! I compiled dt.img from my msm8226-g2mds.dtb file in /arch/arm/boot/. But after I repacked boot.img and replaced dt.img in it and flash my phone did not boot! If I repack boot.img with stock dt.img phone working. In what can be problem?
This is my kernel sources: https://github.com/NikitaProAndroid/android_kernel_lge_msm8226_g2mds/tree/cm-12.x
My stock dt.img: https://yadi.sk/d/0N-k6tK2g38ys
My own compiled dt.img: https://yadi.sk/d/li7GgtCQg396M

And what is VERy strange - they have the same size in bytes!!
But with stock phone starting, with my - not starting...

**Comment by NikitaProAndroid** [comment]
I fix this problem using dtbToolCM with -2 parameter.

**Comment by xiaolu** [comment]
Ok.

**Comment by pinglanke** [comment]
@ziyouwa 我发现，在我的电脑分区文件系统为reiserfs时，d_type始终为0。那么，很可能是文件系统的问题。

**Comment by dyteso** [comment]
@xiaolu I am tried for a long time with this tool.
I failed and failed to create dt.img using dtbTool.
Today I tried dtbToolCM and it creates the dt.image succesfully.
- what is the difference of dtbToolCM and dbtTool ?
Thanks
