### ISSUE TITLE
mkbootimg: 没有那个文件或目录

### ISSUE THREAD

**Issue by ruisiorg** [xiaolu/mkbootimg_tools#25]
./mkboot: 行 101: mkbootimg: 没有那个文件或目录
Make boot.img Error! pls check img_info file

这个不知道是什么意思，检查了info没看出来是哪个文件不存在啊。

**Comment by xiaolu** [comment]
你没有安装依赖库 
sudo apt-get install git-core gnupg flex bison gperf build-essential \
  zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
  lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
  libgl1-mesa-dev libxml2-utils xsltproc unzip

**Comment by ruisiorg** [comment]
感谢！
昨晚本想上微博向你求助的，结果帐号被冻结了，发了三次验证短信都说我帐号被盗要修改密码，可我明明可以用来登录的密码在修改时却又说当前密码错误，想不到你今天就上线了。

**Comment by xiaolu** [comment]
@ruisiorg 你解锁bl了吗？

**Comment by ruisiorg** [comment]
没解锁，不动boot的话刷机后是可以进系统的，动了boot后才进不了系统。
