### ISSUE TITLE
repacking file size mismatch

### ISSUE THREAD

**Issue by s0i37** [xiaolu/mkbootimg_tools#37]
Hello.
After rebuilding kernel (without modification) and building back I have a huge loss of resulting boot.img:
```
boot.img - 128M
new_boot.img - 17M
```
Is it normal behavior? Because I can't load resulting image.

**Comment by brianmason667** [comment]
i have the same issue, adding up the sizes though the new_boot.img is the size of kernel+ramdisk in the folder, maybe its not pulling everything out of boot.img?

**Comment by s0i37** [comment]
After repacking boot.img with https://github.com/osm0sis/AnyKernel3 (used all modern kernel installers for TWRP) I have obtained the same result. However I have managed successfully load it with fastboot.
It seems it is normally.
Backup of stock boot partition has 90% 0-bytes:
![temp](https://user-images.githubusercontent.com/22872513/80923719-b9379c00-8d9e-11ea-8db6-5c648dbb1255.png)
